# Generated by Django 5.0.1 on 2024-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='category',
            field=models.CharField(blank=True, choices=[('COOKING', 'Cooking'), ('TRAVEL', 'Travel'), ('FASHION', 'Fashion'), ('TECHNOLOGY', 'Technology'), ('EDUCATION', 'Education'), ('ART', 'Art')], max_length=20, null=True),
        ),
    ]
